package com.yyyplot.dailytime.enums;

public enum WorkerErrorCode {
    MODEL_CONFIGURATION_ERROR,
    MODEL_REQUEST_FAILED,
    MODEL_INVALID_OUTPUT,
    BROWSER_UNAVAILABLE,
    SEARCH_TIMEOUT,
    INSUFFICIENT_RESULTS,
    DOWNLOAD_FAILED,
    INVALID_MEDIA,
    RENDER_TIMEOUT,
    FFMPEG_FAILED,
    INVALID_WORKER_RESPONSE,
    WORKER_PROCESS_FAILED,
    WORKER_INTERRUPTED,
    INTERNAL_ERROR
}
